destination: ./_site
auto:        false
lsi:         false
server_port: 4042
pygments:    true
markdown:    maruku
permalink:   pretty
maruku:
  use_tex:  false
  use_divs: false
  png_dir:  images
  png_url:  /images
